# Generated by Django 5.0.2 on 2024-03-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_dars_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default=1, upload_to='card/image/'),
            preserve_default=False,
        ),
    ]
