# Generated by Django 5.0.2 on 2024-03-06 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_dars_app', '0002_card_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='batafsil',
        ),
        migrations.CreateModel(
            name='Mavzu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_dars_app.card')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/videos/')),
                ('title', models.CharField(max_length=150)),
                ('mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_dars_app.mavzu')),
            ],
        ),
    ]
