# Generated by Django 5.0.2 on 2024-03-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_dars_app', '0003_remove_card_batafsil_mavzu_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='mavzu',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mavzular', to='video_dars_app.card'),
        ),
    ]
