# Generated by Django 5.0.3 on 2024-03-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_dars_app', '0005_video_image_alter_video_mavzu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='video/images/'),
        ),
    ]
